spring:
  http:
    multipart:
      max-request-size: 1024Mb
      max-file-size: 200Mb
  data:
    hbase:
      quorum: 192.168.1.21,192.168.1.22,192.168.1.23
      zkClientPort: 2181
  resources:
    # 静态资源路径
    static-locations: file:static/
  datasource:
      url: jdbc:mysql://localhost:3306/test
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver



server:
  port: 8888



kafka:
  consumer:
    servers: 192.168.1.92:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: mhd-notice
    group:
      id: mhd-notice
    concurrency: 10
  producer:
    servers: 192.168.1.92:9092
    retries: 0
    batch:
      size: 94096
    linger: 1
    buffer:
      memory: 940960
